DROP SCHEMA IF EXISTS COPA_LIBERTADORES;
CREATE SCHEMA IF NOT EXISTS COPA_LIBERTADORES;
USE COPA_LIBERTADORES;

DROP TABLE IF EXISTS PAISES;
CREATE TABLE IF NOT EXISTS PAISES
(
`idPais` INT NOT NULL AUTO_INCREMENT,
`nombrePais` VARCHAR(50) NOT NULL,
PRIMARY KEY (`idPais`)
);


DROP TABLE IF EXISTS FASES;
CREATE TABLE IF NOT EXISTS FASES
(`idFase` INT NOT NULL AUTO_INCREMENT,
`nombreFase` VARCHAR(50) NOT NULL,
PRIMARY KEY (`idFase`)
);

DROP TABLE IF EXISTS EQUIPOS;
CREATE TABLE IF NOT EXISTS EQUIPOS
(
`idEquipo` INT NOT NULL AUTO_INCREMENT,
`nombreEquipo` VARCHAR(50) NOT NULL,
`paisEquipo` VARCHAR(50) NOT NULL,
`colorEquipo` VARCHAR(50),
`sociosEquipo` INT,
`estadioEquipo` VARCHAR(50),
PRIMARY KEY (`idEquipo`)
);

DROP TABLE IF EXISTS TORNEOS;
CREATE TABLE IF NOT EXISTS TORNEOS
(
`idTorneo` INT NOT NULL AUTO_INCREMENT,
`añoEdicion` INT NOT NULL,
`fase` VARCHAR(50),
`equipoCampeon` VARCHAR(50),
PRIMARY KEY (`idTorneo`)
);


DROP TABLE IF EXISTS JUGADORES;
CREATE TABLE IF NOT EXISTS JUGADORES
(
`idJugador` INT NOT NULL AUTO_INCREMENT,
`nombreJugador` VARCHAR(50) NOT NULL,
`apellidoJugador` VARCHAR(50) NOT NULL,
`nacionalidad` VARCHAR(50),
`edad` INT,
`equipoJugador` VARCHAR(50),
`posicion` VARCHAR(50) NOT NULL,
`pegada` ENUM('DIESTRO','ZURDO'),
`golesJugador` INT,
`amonestaciones` INT,
`expulsiones` INT,
PRIMARY KEY(`idJugador`)
);

DROP TABLE IF EXISTS PARTIDOS;
CREATE TABLE IF NOT EXISTS PARTIDOS
(
    `idPartido` INT NOT NULL AUTO_INCREMENT,
    `añoEdicion` INT NOT NULL,
    `fecha` datetime,
    `estadio` VARCHAR (50),
    `equipoVisitante` VARCHAR (50) NOT NULL,
    `equipoLocal` VARCHAR (50) NOT NULL,
    `golesVisitante` VARCHAR (50) NOT NULL,
    `golesLocal` INT,
    `resultado` ENUM('LOCAL','VISITANTE','EMPATE','SUSPENDIDO') NOT NULL,
    PRIMARY KEY(`idPartido`)
);


ALTER TABLE PAISES ADD INDEX(`nombrePais`);
ALTER TABLE FASES ADD INDEX(`nombreFase`);
ALTER TABLE EQUIPOS ADD INDEX(`nombreEquipo`);
ALTER TABLE EQUIPOS ADD INDEX(`estadioEquipo`);
ALTER TABLE EQUIPOS ADD INDEX(`idEquipo`);
ALTER TABLE TORNEOS ADD INDEX(`añoEdicion`);

ALTER TABLE EQUIPOS ADD CONSTRAINT `paisEquipo` FOREIGN KEY (`paisEquipo`) REFERENCES `PAISES`(`nombrePais`);
ALTER TABLE TORNEOS ADD CONSTRAINT `faseTorneo` FOREIGN KEY (`fase`) REFERENCES `FASES`(`nombreFase`);
ALTER TABLE TORNEOS ADD CONSTRAINT `campeon` FOREIGN KEY (`equipoCampeon`) REFERENCES `EQUIPOS`(`nombreEquipo`);
ALTER TABLE JUGADORES ADD CONSTRAINT `paisJugador` FOREIGN KEY (`nacionalidad`) REFERENCES `PAISES`(`nombrePais`);
ALTER TABLE JUGADORES ADD CONSTRAINT `equipoJugador` FOREIGN KEY (`equipoJugador`) REFERENCES `EQUIPOS`(`nombreEquipo`);
ALTER TABLE PARTIDOS ADD CONSTRAINT `año` FOREIGN KEY (`añoEdicion`) REFERENCES `TORNEOS`(`añoEdicion`);
ALTER TABLE PARTIDOS ADD CONSTRAINT `estadioParido` FOREIGN KEY (`estadio`) REFERENCES `EQUIPOS`(`estadioEquipo`);
ALTER TABLE PARTIDOS ADD CONSTRAINT `local` FOREIGN KEY (`equipoLocal`) REFERENCES `EQUIPOS`(`nombreEquipo`);
ALTER TABLE PARTIDOS ADD CONSTRAINT `visitante` FOREIGN KEY (`equipoVisitante`) REFERENCES `EQUIPOS`(`nombreEquipo`);