DROP TABLE IF EXISTS LOG_AUDITORIA;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA
(
ID_LOG INT AUTO_INCREMENT,
NOMBRE_DE_ACCION VARCHAR (50),
NOMBRE_TABLA VARCHAR(50),
USUARIO VARCHAR(100),
FECHA_UPD_INS_DEL DATE,
PRIMARY KEY (ID_LOG)
);

DROP TABLE IF EXISTS LOG_AUDITORIA2;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA2
(
ID_LOG INT AUTO_INCREMENT,
NOMBREJUGADOR VARCHAR(50),
APELLIDOJUGADOR VARCHAR(50),
EQUIPOJUGADOR VARCHAR(50),
NOMBRE_DE_ACCION VARCHAR (50),
NOMBRE_TABLA VARCHAR(50),
USUARIO VARCHAR(100),
FECHA_UPD_INS_DEL DATE,
PRIMARY KEY (ID_LOG)
);

DROP TRIGGER IF EXISTS TRG_LOG_JUGADOR;
DELIMITER //
CREATE TRIGGER TRG_LOG_JUGADOR AFTER INSERT ON JUGADORES
FOR EACH ROW
BEGIN
INSERT INTO LOG_AUDITORIA (NOMBRE_DE_ACCION,NOMBRE_TABLA,USUARIO,FECHA_UPD_INS_DEL)
VALUES ('INSERT', 'JUGADOR', CURRENT_USER(),NOW());
END
// DELIMITER;

DROP TRIGGER IF EXISTS TRG_MODIF_JUGADOR;
DELIMITER //
CREATE TRIGGER TRG_MODIF_JUGADOR AFTER UPDATE ON JUGADORES
FOR EACH ROW
BEGIN
INSERT INTO LOG_AUDITORIA2 (nombreJugador, apellidoJugador, equipoJugador, NOMBRE_DE_ACCION,NOMBRE_TABLA,USUARIO,FECHA_UPD_INS_DEL)
VALUES (NEW.nombreJugador,NEW.apellidoJugador,NEW.equipoJugador,'UPDATE', 'JUGADOR', CURRENT_USER(),NOW());
END
// DELIMITER ;
